[package]
name = "ronome"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.10.0"
monome-rs = "1.1.3"
num = "0.4.1"
rand = "0.8.5"
